name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubantu-latest
    steps:
       - name: Print "Greetings"
         run: echo "Hello Github"
       - name: Print "GoodBye"
         run: echo "Bye-Bye"
